# Generated by Django 5.2.17 on 2026-08-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['id']},
        ),
    ]
