# Generated by Django 5.2.17 on 2026-08-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_review'),
        ('shopping_list', '0002_alter_shoppinglistitem_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.UniqueConstraint(fields=('shopping_list', 'ingredient', 'unit'), name='shoppinglistitem_unique_ingredient_unit'),
        ),
    ]
