# Generated by Django 5.2.17 on 2026-08-20 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='recipes.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_tags', to='recipes.tag')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('recipe', 'order'), ('recipe', 'tag')},
            },
        ),
    ]
