# Generated by Django 5.2.17 on 2026-08-22 02:28

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
