# Generated by Django 5.2.17 on 2026-08-24 19:02

from django.conf import settings
from django.db import migrations, models
from django.db.models import Avg, Count, OuterRef, Subquery, Value
from django.db.models.functions import Coalesce


def backfill_rating_aggregates(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    Review = apps.get_model('recipes', 'Review')

    review_stats = (
        Review.objects.filter(recipe_id=OuterRef('pk'))
        .order_by()
        .values('recipe_id')
    )
    Recipe.objects.update(
        avg_rating=Subquery(review_stats.annotate(v=Avg('rating')).values('v')),
        review_count=Coalesce(
            Subquery(
                review_stats.annotate(v=Count('id')).values('v'),
                output_field=models.PositiveIntegerField(),
            ),
            Value(0),
        ),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='recipes_rec_name_891f25_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_at'], name='recipes_rec_created_a55f59_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['avg_rating'], name='recipes_rec_avg_rat_477369_idx'),
        ),
        migrations.RunPython(backfill_rating_aggregates, noop_reverse),
    ]
